// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using shortenyour.link.Data;

#nullable disable

namespace shortenyour.link.Migrations.Mods
{
    [DbContext(typeof(ModsContext))]
    partial class ModsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SYL_Admin.Models.Mods", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Maintenance")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UnderAttack")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("mods");
                });
#pragma warning restore 612, 618
        }
    }
}
